### ISSUE TITLE
Viewport Watch in Scrollable Container

### ISSUE THREAD

**Issue by hemlok** [wix/angular-viewport-watch#9]
I'm having an issue where my viewport watch is not updating when the content scrolls into view in a scrollable container. Any ideas on how to address this?

**Comment by adeopura4** [comment]
So I had to do a couple of things to resolve this. I do not claim that these are perfect solutions, but they do work. 

Firstly, in the scrollMonitor.js, remove the if condition within the calculateViewport function. In other words, always call the code within the if condition.

Secondly, in scrollMonitor.js, change window.addEventListener('scroll', scrollMonitorListener); to window.addEventListener('scroll', scrollMonitorListener, true);. This will ensure that the window always receives the scroll event.

**Comment by amirgon** [comment]
@adeopura4  your suggestion seems to partly work.  
Number of watchers is very high when the page is loaded before the scrollbar is touched. Only once scrollbar is touched, the number of watchers drop.  

btw, why don't you make a pull request to [scrollMonitor](https://github.com/stutrek/scrollMonitor)?

**Comment by tenderloin420** [comment]
scrollMonitor works with scrolling containers. Check out their docs for the `createContainer` method:

    var containerMonitor = scrollMonitor.createContainer(elem.parent());
    elementWatcher = containerMonitor.create(elem, scope.$eval(attrs.viewportWatch || '0'));
